trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CODEQL_RUN_AUTOBUILD: true

stages:
  - stage: CodeQL
    displayName: CodeQL Analysis
    jobs:
      - job: Analyze
        displayName: Analyze
        steps:
          - checkout: self
            fetchDepth: 0

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node 20'

          - script: |
              if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm i; fi
              npm run -s build --workspaces --if-present || true
            displayName: 'Install and build'

          - task: CodeQL3000Init@0
            displayName: 'Initialize CodeQL'
            inputs:
              languages: 'javascript'

          - task: CodeQL3000Analyze@0
            displayName: 'Perform CodeQL Analysis'
