apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: production
  labels:
    app: chat-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
        tier: backend
    spec:
      containers:
      - name: chat-service
        image: studysphereacr.azurecr.io/chat-service:latest
        ports:
        - containerPort: 5004
          name: http
        envFrom:
        - secretRef:
            name: azure-secrets
        env:
        - name: PORT
          value: "5004"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5

