apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: production
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP
    name: http
  selector:
    app: chat-service

