apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: production
  labels:
    app: group-service
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: group-service

